-- phpMyAdmin SQL Dump
-- version 4.8.0
-- https://www.phpmyadmin.net/
--
-- Хост: 127.0.0.1
-- Время создания: Дек 23 2018 г., 15:25
-- Версия сервера: 10.1.31-MariaDB
-- Версия PHP: 7.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- База данных: `product`
--

-- --------------------------------------------------------

--
-- Структура таблицы `product`
--

CREATE TABLE `product` (
  `id` int(11) NOT NULL,
  `type` varchar(256) NOT NULL,
  `name` varchar(256) NOT NULL,
  `rec` text NOT NULL,
  `image_one` varchar(256) NOT NULL,
  `image_two` varchar(256) NOT NULL,
  `image_three` varchar(256) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Дамп данных таблицы `product`
--

INSERT INTO `product` (`id`, `type`, `name`, `rec`, `image_one`, `image_two`, `image_three`) VALUES
(2, 'Soup', 'Mushroom soup', 'INGREDIENTS 4 Tbsp olive oil 4 Tbsp butter 2 pounds (900 g) cremini (or button) mushrooms, cleaned, roughly chopped or sliced 1/8-inch thick Small handful of shiitake mushrooms (chopped) 3/4 cup minced shallots (6 ounces, 170 g) 3 cloves garlic, minced (3 teaspoons) 1 teaspoon kosher salt 3/4 teaspoon dried tarragon 4 cups (1 liter) chicken stock (or vegetable stock for vegetarian option) 1/2 cup (120 ml) heavy cream 1/2 teaspoon freshly ground black pepper (more or less to taste) METHOD 1.Sauté the mushrooms: Heat olive oil on medium high heat in a 5-6 quart thick-bottomed pot. When the oil is hot, swirl in the butter. Once the butter has melted, add the mushrooms, stir to coat with the olive oil and butter. Cook the mushrooms on medium high heat until they are lightly browned and have released most of their water, about 10 minutes. Remove 1 cup of the cooked mushrooms from the pot and set aside (they will be added back in later). 2.Add shallots, garlic: Reduce heat to medium. Add the minced shallots and the garlic to the pot, stir to combine, cook for about a minute. 3.Add salt, tarragon, stock: Add the salt, dried tarragon, and the stock to the pot. Increase the heat to medium high, bring to a simmer and cook, uncovered, for 10 minutes. Remove from heat. Then return to the pot. (If the soup is too thick for you, add some water or more stock to thin the soup to the desired level of thickness.) 4.Stir in cream and reserved mushrooms: Whisk the cream into the soup and add the black pepper. Adjust salt and pepper to taste. Stir in the reserved cooked mushrooms.', 'mushroom1.jpg', 'mushroom2.jpg', 'mushroom3.jpg'),
(3, 'Salat', 'Caesar', 'INGREDIENTS 1/2 cup high quality extra virgin olive oil 4 cloves fresh garlic, peeled, smashed, then minced 1 baguette, preferably a day old, sliced thin 1/4 cup freshly juiced lemon juice (plus more to taste) 4 ounces Parmesan cheese, grated 1 teaspoon anchovy paste, or 1-2 anchovies, smashed and minced 2 eggs Freshly ground black pepper (1/4 teaspoon or to taste) 1/2 teaspoon salt 4-6 small heads of romaine lettuce, rinsed, patted dry, wilted outer leaves discarded METHOD 1.In a very large bowl, whisk together the olive oil and garlic. Let sit for half an hour. 2.Make the toasted croutons: While the oil is sitting, make the croutons. Spread the baguette slices out over a baking sheet (may need to do in batches), lined with parchment paper or a silicone mat. Brush or spray with olive oil (or melted butter, or if you want garlicky croutons, dip pastry brush in the garlic infused oil you have sitting in step 1). Broil for a couple of minutes until the tops are lightly browned. (Note: do not walk away, these can easily go from browned to burnt.) Remove and let cool. 3.Make the dressing: Add anchovies and eggs to the oil garlic mixture. Whisk until creamy. Add salt and pepper and 1/4 cup of lemon juice. Whisk in half of the Parmesan cheese. Taste, add more lemon juice to taste. The lemon should give an edge to the dressing, but not overwhelm it. 4.Tear off chunks of romaine lettuce: Using your hands, tear off chunks of lettuce from the heads of romaine lettuce (do not use a knife to cut). Add to the oil mixture and toss until coated. Add the rest of the Parmesan cheese, toss. 5.Coarsely chop the toasted bread and add (with the crumbs from the chopping) to the salad. Toss. Serve immediately.', 'caesar1.png', 'caesar2.png', 'caesar3.png'),
(4, 'Salat', 'Caesar', 'INGREDIENTS 1/2 cup high quality extra virgin olive oil 4 cloves fresh garlic, peeled, smashed, then minced 1 baguette, preferably a day old, sliced thin 1/4 cup freshly juiced lemon juice (plus more to taste) 4 ounces Parmesan cheese, grated 1 teaspoon anchovy paste, or 1-2 anchovies, smashed and minced 2 eggs Freshly ground black pepper (1/4 teaspoon or to taste) 1/2 teaspoon salt 4-6 small heads of romaine lettuce, rinsed, patted dry, wilted outer leaves discarded METHOD 1.In a very large bowl, whisk together the olive oil and garlic. Let sit for half an hour. 2.Make the toasted croutons: While the oil is sitting, make the croutons. Spread the baguette slices out over a baking sheet (may need to do in batches), lined with parchment paper or a silicone mat. Brush or spray with olive oil (or melted butter, or if you want garlicky croutons, dip pastry brush in the garlic infused oil you have sitting in step 1). Broil for a couple of minutes until the tops are lightly browned. (Note: do not walk away, these can easily go from browned to burnt.) Remove and let cool. 3.Make the dressing: Add anchovies and eggs to the oil garlic mixture. Whisk until creamy. Add salt and pepper and 1/4 cup of lemon juice. Whisk in half of the Parmesan cheese. Taste, add more lemon juice to taste. The lemon should give an edge to the dressing, but not overwhelm it. 4.Tear off chunks of romaine lettuce: Using your hands, tear off chunks of lettuce from the heads of romaine lettuce (do not use a knife to cut). Add to the oil mixture and toss until coated. Add the rest of the Parmesan cheese, toss. 5.Coarsely chop the toasted bread and add (with the crumbs from the chopping) to the salad. Toss. Serve immediately.', 'caesar1.png', 'caesar2.png', 'caesar3.png'),
(5, 'Salat', 'Greek', 'INGREDIENTS 6 Tbsp olive oil 2 Tbsp fresh lemon juice 1/2 teaspoon fresh chopped garlic 1 teaspoon red wine vinegar 1/2 teaspoon dried oregano or 1 teaspoon chopped fresh oregano 1/2 teaspoon dill weed or 1 teaspoon chopped fresh dill Salt and freshly ground black pepper 3 large plum tomatoes, seeded, coarsely chopped 3/4 cucumber, peeled, seeded, coarsely chopped 1/2 red onion, peeled, chopped 1 bell pepper, seeded, coarsely chopped 1/2 cup pitted black olives (preferably brine-cured), coarsely chopped A heaping half cup crumbled feta cheese METHOD 1.Make dressing: Whisk the olive oil, lemon juice, garlic, vinegar, oregano and dill weed together until blended. Season to taste with salt and freshly ground black pepper. (Can be prepared 3 hours ahead. Let stand at room temperature. Re-whisk before using.)2.Combine salad ingredients: Combine the tomatoes, cucumber, onion, bell pepper, olives in a bowl. Toss with dressing. Sprinkle cheese over and serve.', 'greek1.jpg', 'greek2.jpg', 'greek3.jpg'),
(6, 'Salat', 'curried', 'INGREDIENTS For the salad: 4 bone-in split chicken breasts, or 4 bone-in whole chicken legs, or a combination (3 pounds total) 4 cups water 1 teaspoon salt 1 cup whole almonds (skinned or blanched) 1 ripe mango 1/2 tart green apple 2 stalks celery 1 1/2 cups seedless red or green grapes 3 tablespoons chopped fresh cilantro 6 scallions 1/2 cup golden raisins For the curry dressing: 2 tablespoons canola oil 1 1/2 tablespoons curry powder 1 tablespoon tomato paste 1 cup mayonnaise 1/2 teaspoon salt 1/4 teaspoon ground black pepper 1 1/2 tablespoons cider vinegar, plus more to taste 1 tablespoon lemon juice METHOD 1.Cook and cool the chicken: In a Dutch oven or large sauce pan, combine the chicken pieces, water, and 1 teaspoon of the salt. Bring to a boil, skim the surface thoroughly, and reduce the heat to low. 2.Cover the pan and simmer the chicken for 30 minutes, rotating the bottom pieces to the top halfway through cooking. Cook until the chicken is cooked through and registers 165°F with an instant read thermometer in the thickest part.', 'curried1.png', 'curried2.png', 'curried3.png'),
(7, 'Salat', 'shrimp', 'INGREDIENTS Creamy Cilantro Lemon Dressing ¼ cup paleo mayonnaise 3 Tbsp minced cilantro 1 Tbsp water 2 tsp fresh lemon juice Zest of 1 lemon ¼ tsp garlic powder ½ tsp sea salt Coastal Cobb Salad 6 cups chopped romaine lettuce 6 oz cooked shrimp 4 oz cooked chicken breast, sliced 2 boiled eggs, halved ¼ cup crumbled cooked bacon 1 avocado, chopped 1 cup grape or cherry tomatoes, halved ½ cup chopped cilantro 1 green onion, sliced METHOD 1.Creamy Cilantro Lemon Dressing Mix all ingredients together by hand or blend using an immersion blender or food processor. I recommend using an immersion blender. 2.Store under refrigeration until needed. 3.Coastal Cobb Salad Assemble salad on a large platter. Line the platter with romaine lettuce and then arrange the toppings. Serve with creamy cilantro lemon dressing.', 'shrimp1.jpg', 'shrimp2.jpg', 'shrimp3.jpg'),
(8, 'Salat', 'rainbow', 'INGREDIENTS 1 pound dry pasta (I used tri-color rotini) 4-6 cups chopped antipasto ingredients (I used diced salami, mozzarella, cherry tomatoes, olives, artichoke hearts, pepperoncini, roasted red peppers. See below for more ideas.*) 1 cup chopped fresh kale, massaged** quarter of a small red onion, peeled and thinly-sliced 1 batch Italian Herb Vinaigrette (see below) 1/3 cup extra-virgin olive oil 1/4 cup red-wine vinegar 2 teaspoons McCormick Italian Blend Herb Grinder Italian seasoning, or homemade 1/2 teaspoon Kosher salt 1/2 teaspoon freshly-cracked black pepper 1/4 teaspoon garlic powder METHOD 1.Cook the pasta in a large stockpot of generously-salted water al dente according to package directions. Drain pasta and rinse under cold water for about 20-30 seconds until no longer hot. 2.In a large bowl, combine the cooked pasta, antipasto ingredients, kale, and onion. Drizzle the Italian Herb Vinaigrette on top, then toss to combine. Serve immediately, or cover and refrigerate for up to 3 days. TO MAKE THE ITALIAN HERB VINAIGRETTE: Whisk all ingredients together until combined. 3.To soften the kale, I placed it in the mixing bowl first, along with 2 tablespoons of the vinaigrette, and then used my hands to massage the vinaigrette into the kale for about 1 minute. This makes it considerably softer, and will turn the kale a nice dark green color.', 'rainbow1.jpg', 'rainbow2.jpg', 'rainbow3.jpg'),
(9, 'Salat', 'spinach', 'INGREDIENTS 1 heaping cup (4 ounces) miniature penne pasta measured dry 1 cup prepared chicken leftover marinated and grilled chicken or leftover rotisserie chicken 4 ounces baby spinach stems removed 1 cup cherry tomatoes halved ¨÷ cup crumbled feta cheese ¨÷ cup slivered almonds toasted 1 large orange 2 teaspoons zest; 4 tablespoons juice 1 large lemon ¨ö teaspoon zest; 2 tablespoons juice 3 tablespoons honey 2 teaspoons Dijon mustard do not use regular ¨ö teaspoon fine sea salt ¨ö cup olive oil vegetable oil or canola oil can also be used Optional: freshly cracked pepper, fresh parsley METHOD 1.Cook the pasta according to package direction. Drain and then rinse with cold water. 2.Place the cooled pasta in a large bowl. Add in the spinach and the halved cherry tomatoes. 3.Briefly warm up and then coarsely chop the leftover grilled chicken. Add to salad and toss to combine. 4.Lightly toast the almonds over a skillet on medium heat until fragrant. Sprinkle the almonds and feta cheese over the salad. 5.For the dressing: combine all of the ingredients together except for the oil in a blender. Blend until all ingredients are well incorporated. Slowly add in the oil in a steady stream and pulse until combined. Toss the salad with the dressing (to taste; you may not want/need all of it) and enjoy.', 'spinach1.jpg', 'spinach2.jpg', 'spinach3.jpg'),
(10, 'Steak', 'rolled steak', 'INGREDIENTS Marinade: 1/4 cup extra virgin olive oil 1/4 cup red wine vinegar 2 cloves of garlic, finely chopped 2 Tbsp chopped fresh parsley 1/4 teaspoon coarse black pepper Flank steak: 1 flank steak (3/4 in thick, about 1 1/4 pounds), butterflied 2 red bell peppers 3 Tbsp chopped parsley 6 to 8 thin slices of prosciutto or other cured ham 24 medium sized fresh basil leaves 2 Tbsp grated Parmesan cheese Freshly ground pepper to taste 1 bunch watercress or baby arugula for garnish METHOD 1.Butterfly the steak: To butterfly the steak, orient it first so that the meat grain is running up and down in front of you. (The short edge of the steak is facing you.) Place your hand on top of the meat. Using a long, sharp knife, make a long, horizontal cut on the long side of the steak, cutting the meat in half, and going almost all the way across, leaving 1-inch at the edge uncut (the hinge). The butterfly hinge should be in the same direction as the grain of the meat. (Choose the longest straightest side of the steak as the hinge side, and the roundest most curved side as the side to start the cut.) Open the flaps of the steak. You can even out the middle if you want so that the center is not as thick. 2.Assemble the marinade and marinate the steak for 2 hours. Make sure to coat the inside of the butterflied flank steak with the marinade as well. 3.Roast the bell peppers: Cut bell peppers in half and remove the stems and seed pods. Rub the outside of the bell pepper halves with olive oil and place on a lined baking sheet, cut side down, under a broiler. Broil the halved red bell peppers until peel is black. Remove from the oven, place in a bowl and cover with a plate. After about 5 minutes, remove and discard the blackened peel. 4.Layer steak with red bell pepper, parsley, prosciutto, basil, Parmesan: Preheat oven to 350°F. Remove steak from marinade, reserve the marinade. Layer the steak with prosciutto slices, roasted red bell pepper, parsley, and basil leaves, leaving at least an inch bare at the ends. Sprinkle with Parmesan and pepper. 5.Roll up the steak: Starting with one of the long ends, roll meat up like a jellyroll; grain of steak should run length of roll. Tie in 2-3 inch intervals with kitchen string. Place in shallow baking dish and spread any remaining marinade over the top. 6.Bake: Bake at 350°F for 30 minutes. Let rest 15 minutes before serving. Cut into 1/2-inch to 1-inch thick slices, garnish with watercress or baby arugula.', 'rulet1.jpg', 'rulet2.jpg', 'rulet3.jpg'),
(11, 'Steak', 'steak', 'INGREDIENTS For the steak: 1 1/2-inch thick ribeye, bone in or out (about 1 1/2 lbs. without the bone) 3/4 teaspoon coarse sea salt or kosher salt 1 teaspoon freshly ground pepper For the herb butter sauce: 4 tablespoons butter Leaves from 4 sprigs of thyme 1 tablespoon minced fresh rosemary 1 clove garlic, minced 1 shallot, about half the size of a golf ball, minced METHODHIDE PHOTOS 1.Trim the fat: Remove the outer layer of fat from the ribeye. The interior marbling will flavor the meat, whereas the outer fat layer will produce flare ups on the grill, which can add a burnt (not charred) flavor to the steak. 2.Season the steak and refrigerate: Pat the steak dry with a paper towel. This removes surface moisture and will help you achieve a good sear. Season each side with salt and pepper and rub them in a bit. Put the steak in the fridge, uncovered, for at least an hour and up to 48 hours. 3.Make the herbed butter: In a small saucepan, add butter, herbs, garlic, and shallots. Melt over low heat. Do this at least 10 minutes before you are ready to put the steak on the grill. The longer the herbs sit in the butter, the longer the flavors will infuse. You can also make this butter up to 2 hours beforehand; if so, cover and refrigerate. Gently reheat the butter to melt it again before you put the steaks on the grill. 4.Preheat the grill: Prepare a charcoal grill for two-zone grilling, so half is hot and one half is warm. The grill is hot when you can only hold your hand over the hot zone for a second or two. On a gas grill, heat the grill to 450°F with two burners going, which should only take about 10 minutes, then turn one of the burners down to medium to create two cooking zones. 5.Cook and baste the steak: Add the steak to the hottest side of the grill. Close the lid and sear for 2 minutes. Open the lid, flip the steak, and baste it with the melted herb butter and herbs. Close the lid. Cook for 2 additional minutes. Flip the steak again and move it to a lower heat side. Baste it again with butter. Continue flipping and basting every two minutes for the next 6 minutes, closing the lid between each flip. After the steak has been on the grill for a total of 10 minutes (for medium-rare steak), transfer it to a clean platter; it should read 137°F to 140°F internally. Baste it again with butter. (Continue cooking for longer if you prefer your steak more well-done.) 6.Let the steak rest: Let it rest for 5 minutes; it will climb another few degrees as it sits and the juices will redistribute. 7.Slice and serve the steak: Slice the steak against the grain. Pour any remaining herb butter sauce over top and serve.', 'steak1.jpg', 'steak2.jpg', 'steak3.jpg');

--
-- Индексы сохранённых таблиц
--

--
-- Индексы таблицы `product`
--
ALTER TABLE `product`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT для сохранённых таблиц
--

--
-- AUTO_INCREMENT для таблицы `product`
--
ALTER TABLE `product`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
